// import Nav from '@/components/Nav'
import Head from "next/head";
import Navbar from "./Navbar";
import Footer from "./Footer";


export default function Layout({children}) {

  return (
    <>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className='bg-blue-600 min-h-screen flex'>
        <Navbar />
      <div className='bg-white flex-grow mt-2 mb-2 mr-2 rounded-lg p-4'>{children}</div>
      <Footer />
    </div>
    </>
  );
}
